### ISSUE TITLE
VSIX does not load into VS 2019 preview 4

### ISSUE THREAD

**Issue by jackfoxy** [szehetner/InliningAnalyzer#15]
Admittedly I am trying this on an F# project (which is probably not supported.
In VS 2017 I do get the Inlining Analyzer menu item in Tools, but not in VS2019 Preview r

**Comment by szehetner** [comment]
VS 2019 is not supported yet. I don't expect any problems with it, but I just haven't gotten around to upgrading the package and testing it. I hope to do this next week, but definitely before the release.

**Comment by szehetner** [comment]
I have just published a new version that supports VS 2019 as well.
