### ISSUE TITLE
NullReferenceException when running analysis

### ISSUE THREAD

**Issue by GSPP** [szehetner/InliningAnalyzer#18]
The output window is showing the following error message:

<hr>

Starting Inlining Analyzer...
Assembly: x.dll
Runtime: NetFramework
Platform: X64
Scope: All Types and Methods

Method A.B(generic class C`1<!!0>  (class System.Func`1<!!0>)) could not be found.
System.NullReferenceException: Object reference not set to an instance of an object.
   at InliningAnalyzer.EtwSignatureMapper.GetTypename(Type type)
   at InliningAnalyzer.EtwSignatureMapper.ParametersMatch(ParameterInfo[] parameters, String[] signatureParameters)
   at InliningAnalyzer.EtwSignatureMapper.SelectOverload(MethodBase[] candidates, String signature)
   at InliningAnalyzer.OrderedMethodProvider.<GetMethods>d__4.MoveNext()
   at InliningAnalyzer.JitCompilerHost.CompileMethods()
   at InliningAnalyzer.JitCompilerHost.PreJITMethods()
Finished Inlining Analyzer

Some code:

        public static C<T> B<T>(Func<T> action)

        public class C
        {
            ..
        }
        public class C<T> : C

<hr>

Is this enough to identify the issue?

**Comment by szehetner** [comment]
Analyzing code inside generic classes or methods is not supported, but this shouldn't throw an exception, especially if you analyze the whole project. I will have a look at this.

**Comment by szehetner** [comment]
I have tried a few variation of this code but couldn't reproduce it. Could you post a more complete example? Is all of this code inside a class A? From where is the method B called?

**Comment by GSPP** [comment]
OK, I debugged the `GetTypename` method. The `type` is `T[]`. It seems to be from this method:

        public static U[] F<T, U>(this T[] array, Func<T, U> selector)
        {
          //...
        }

`type.FullName` is `null` here.

**Comment by szehetner** [comment]
Sorry, still no luck in reproducing this.

I tried it with this code:
```csharp
public static class A
    {
        public static U[] F<T, U>(this T[] array, Func<T, U> selector)
        {
            return array.Select(selector).ToArray();
        }
    }

    public class C
    {
        public void X()
        {
            var o = new C[0];
            o.F<object, string>(s => null);
        }
    }

How is the F method called in your case?

**Comment by GSPP** [comment]
OK, it was a different method... The method that I posted was the only method in the project with the parameter name I got from the debugger. But somehow I got it wrong. I now reproduced the problem in a console app with the following code:

        static void Main(string[] args)
        {
            F(new List<int[]>());
            F(new List<IEnumerable<int>>());
        }
        static IList<IList<T>> F<T>(IList<IEnumerable<T>> items)
        {
            return null;
        }
        static IList<IList<T>> F<T>(IList<T[]> items)
        {
            return null;
        }

I don't understand why your repro code does not work. Maybe the `T[]` must be consumed by another generic type instantiation.

**Comment by szehetner** [comment]
Thanks, with this sample I was able to reproduce and fix it. Be aware that the fix only allows the analyzer to continue, the method calls to F and the contents of these methods are still not analyzed because of the missing support for generic methods.

**Comment by GSPP** [comment]
Great! Can you tell me when an update will be available? I am eager to try it out. The extension is a great idea and the implementation using ETW is quite clever.

**Comment by szehetner** [comment]
I just published a new version with this fix. Could you try it out to see if it works for you now?

**Comment by GSPP** [comment]
Yes, it works. Thanks!
