### ISSUE TITLE
Compile Error, Simd intructions and Pointers

### ISSUE THREAD

**Issue by faruknane** [szehetner/InliningAnalyzer#21]
```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static unsafe void ElementWiseAddAVX(float* ptr_a, float right, float* ptr_res, long length)
        {
            float* ptr_b = &right;
            {
                for (long i = 0; i < length / Vector256<float>.Count * Vector256<float>.Count; i += Vector256<float>.Count)
                {
                    Vector256<float> v1 = Avx2.LoadVector256(&ptr_a[i]);
                    Vector256<float> v2 = Avx2.BroadcastScalarToVector256(ptr_b);
                    Vector256<float> res = Avx2.Add(v1, v2);
                    Avx2.Store(&ptr_res[i], res);
                }
                for (long i = length / Vector256<float>.Count * Vector256<float>.Count; i < length; i++)
                {
                    ptr_res[i] = ptr_a[i] + *ptr_b;
                }
            }
        }
```
This code gives compilation error.

**Comment by szehetner** [comment]
I can reproduce the issue, but will be a few days before I can analyze it in detail.

**Comment by faruknane** [comment]
Okay, I will be waiting your reply then :) thank you

**Comment by faruknane** [comment]
@szehetner Sir, have you looked at the issue?

**Comment by szehetner** [comment]
Yes, the issue occurs if you have .NET Core 3.0 installed but also a .NET Core 2.x version. The analyzer will then be run with the 2.x version which doesn't have the new intrinsics libary. I have now changed the default to always run with the latest installed .NET Core version, but also added an option to specify the .NET Core version explicitly in the options. 

I will publish a new version with this fix over the weekend.

**Comment by faruknane** [comment]
Good Job !

**Comment by szehetner** [comment]
New version has just been published.
