### ISSUE TITLE
Tools -> Inlining Analyzer -> Run inlining analyzer... JitHost.x64 crash

### ISSUE THREAD

**Issue by Krakean** [szehetner/InliningAnalyzer#5]
Hello
Curious, InliningAnalyzer support projects using .NET Core 2.0?
In my case, I getting crash when trrying to run it on one of my project.
If you need project to repro, give me your email, I'll send you for analyzing.

P.S. Please add "Analyze file with InlineAnalyzer" to right-mouse-button menu when you click on file in project, like PVS-Studio: https://i.imgur.com/DfjY59f.png

**Comment by szehetner** [comment]
.NET Core is not supported yet. It is planned though, I just didn't have time to implement it yet. No idea when I can do it, but I hope soon.

I like the idea to be able to start it from the solution explorer as well, I created a new issue to track that seperately.

**Comment by szehetner** [comment]
I actually started looking into this in more detail. It will need .NET Core 2.1 though, as the API I'm using for JIT compilation has only been implemented lately. See https://github.com/dotnet/coreclr/issues/15522.
The .NET Core 2.1 release shouldn't be far away now, so I hope to have it ready then.

**Comment by Krakean** [comment]
>It will need .NET Core 2.1 though

Not a problem at all! :)

>The .NET Core 2.1 release shouldn't be far away now, so I hope to have it ready then.

Nice, looking forward for it

**Comment by szehetner** [comment]
I just uploaded a new version with .Net Core support. Could you give it a try and see if it works with your projects?

You need to have .Net Core 2.1.0-rc1 installed for running the analyzer itself, your projects can have any .Net Core or .Net Standard version.

**Comment by szehetner** [comment]
Closing this as .Net Core support works in my tests (as said, .Net Core 2.1+ is needed).

Please reopen or create another issue if you have any problems with it.
