### ISSUE TITLE
Change Highlighting Colours?

### ISSUE THREAD

**Issue by cocowalla** [szehetner/InliningAnalyzer#7]
Is it possible to configure which colours are used for the highlighting? I'm colourblind, and the colours used are unfortunately too similar for me to easilt discern.

**Comment by szehetner** [comment]
Yes, just search for "Inlining Analyzer" in the "Fonts and Colors" options page:

![Color Settings](https://raw.githubusercontent.com/szehetner/InliningAnalyzer/master/src/VsExtension/Shell/Resources/ColorConfig.png)

**Comment by cocowalla** [comment]
Perfect, thanks!
